# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/examples/desktop/autoflip/calculators/localization_to_region_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/examples/desktop/autoflip/calculators/localization_to_region_calculator.proto',
  package='mediapipe.autoflip',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nWmediapipe/examples/desktop/autoflip/calculators/localization_to_region_calculator.proto\x12\x12mediapipe.autoflip\x1a$mediapipe/framework/calculator.proto\"\xdb\x01\n%LocalizationToRegionCalculatorOptions\x12%\n\x17output_standard_signals\x18\x01 \x01(\x08:\x04true\x12!\n\x12output_all_signals\x18\x02 \x01(\x08:\x05\x66\x61lse2h\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xa1\xe9\xc3\x87\x01 \x01(\x0b\x32\x39.mediapipe.autoflip.LocalizationToRegionCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_LOCALIZATIONTOREGIONCALCULATOROPTIONS = _descriptor.Descriptor(
  name='LocalizationToRegionCalculatorOptions',
  full_name='mediapipe.autoflip.LocalizationToRegionCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_standard_signals', full_name='mediapipe.autoflip.LocalizationToRegionCalculatorOptions.output_standard_signals', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_all_signals', full_name='mediapipe.autoflip.LocalizationToRegionCalculatorOptions.output_all_signals', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.autoflip.LocalizationToRegionCalculatorOptions.ext', index=0,
      number=284226721, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=369,
)

DESCRIPTOR.message_types_by_name['LocalizationToRegionCalculatorOptions'] = _LOCALIZATIONTOREGIONCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocalizationToRegionCalculatorOptions = _reflection.GeneratedProtocolMessageType('LocalizationToRegionCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZATIONTOREGIONCALCULATOROPTIONS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.localization_to_region_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.LocalizationToRegionCalculatorOptions)
  })
_sym_db.RegisterMessage(LocalizationToRegionCalculatorOptions)

_LOCALIZATIONTOREGIONCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _LOCALIZATIONTOREGIONCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_LOCALIZATIONTOREGIONCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
