# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/examples/desktop/autoflip/calculators/shot_boundary_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/examples/desktop/autoflip/calculators/shot_boundary_calculator.proto',
  package='mediapipe.autoflip',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nNmediapipe/examples/desktop/autoflip/calculators/shot_boundary_calculator.proto\x12\x12mediapipe.autoflip\x1a$mediapipe/framework/calculator.proto\"\xde\x02\n\x1dShotBoundaryCalculatorOptions\x12\x17\n\nmin_motion\x18\x01 \x01(\x01:\x03\x30.2\x12\x18\n\rmin_shot_span\x18\x02 \x01(\x01:\x01\x32\x12\x16\n\x0bwindow_size\x18\x03 \x01(\x05:\x01\x37\x12\x1c\n\x10min_shot_measure\x18\x04 \x01(\x01:\x02\x31\x30\x12*\n\x1cmin_motion_with_shot_measure\x18\x05 \x01(\x01:\x04\x30.05\x12#\n\x15output_only_on_change\x18\x06 \x01(\x08:\x04true\x12!\n\x12\x65qualize_histogram\x18\x07 \x01(\x08:\x05\x66\x61lse2`\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xc1\xdc\x8a\x86\x01 \x01(\x0b\x32\x31.mediapipe.autoflip.ShotBoundaryCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_SHOTBOUNDARYCALCULATOROPTIONS = _descriptor.Descriptor(
  name='ShotBoundaryCalculatorOptions',
  full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_motion', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.min_motion', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_shot_span', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.min_shot_span', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='window_size', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.window_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=7,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_shot_measure', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.min_shot_measure', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(10),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_motion_with_shot_measure', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.min_motion_with_shot_measure', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_only_on_change', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.output_only_on_change', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equalize_histogram', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.equalize_histogram', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.autoflip.ShotBoundaryCalculatorOptions.ext', index=0,
      number=281194049, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=491,
)

DESCRIPTOR.message_types_by_name['ShotBoundaryCalculatorOptions'] = _SHOTBOUNDARYCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShotBoundaryCalculatorOptions = _reflection.GeneratedProtocolMessageType('ShotBoundaryCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _SHOTBOUNDARYCALCULATOROPTIONS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.shot_boundary_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.ShotBoundaryCalculatorOptions)
  })
_sym_db.RegisterMessage(ShotBoundaryCalculatorOptions)

_SHOTBOUNDARYCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _SHOTBOUNDARYCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_SHOTBOUNDARYCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
