# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/examples/desktop/autoflip/calculators/signal_fusing_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.examples.desktop.autoflip import autoflip_messages_pb2 as mediapipe_dot_examples_dot_desktop_dot_autoflip_dot_autoflip__messages__pb2
from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/examples/desktop/autoflip/calculators/signal_fusing_calculator.proto',
  package='mediapipe.autoflip',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nNmediapipe/examples/desktop/autoflip/calculators/signal_fusing_calculator.proto\x12\x12mediapipe.autoflip\x1a;mediapipe/examples/desktop/autoflip/autoflip_messages.proto\x1a$mediapipe/framework/calculator.proto\"\xdb\x01\n\x1dSignalFusingCalculatorOptions\x12;\n\x0fsignal_settings\x18\x01 \x03(\x0b\x32\".mediapipe.autoflip.SignalSettings\x12\x1b\n\x0emax_scene_size\x18\x02 \x01(\x05:\x03\x36\x30\x30\x32`\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xd4\xbd\xc7\x85\x01 \x01(\x0b\x32\x31.mediapipe.autoflip.SignalFusingCalculatorOptions\"\xa4\x01\n\x0eSignalSettings\x12,\n\x04type\x18\x01 \x01(\x0b\x32\x1e.mediapipe.autoflip.SignalType\x12\x14\n\tmin_score\x18\x02 \x01(\x02:\x01\x30\x12\x14\n\tmax_score\x18\x03 \x01(\x02:\x01\x31\x12\x1a\n\x0bis_required\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\ronly_required\x18\x05 \x01(\x08:\x05\x66\x61lse'
  ,
  dependencies=[mediapipe_dot_examples_dot_desktop_dot_autoflip_dot_autoflip__messages__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_SIGNALFUSINGCALCULATOROPTIONS = _descriptor.Descriptor(
  name='SignalFusingCalculatorOptions',
  full_name='mediapipe.autoflip.SignalFusingCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal_settings', full_name='mediapipe.autoflip.SignalFusingCalculatorOptions.signal_settings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_scene_size', full_name='mediapipe.autoflip.SignalFusingCalculatorOptions.max_scene_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.autoflip.SignalFusingCalculatorOptions.ext', index=0,
      number=280092372, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=421,
)


_SIGNALSETTINGS = _descriptor.Descriptor(
  name='SignalSettings',
  full_name='mediapipe.autoflip.SignalSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mediapipe.autoflip.SignalSettings.type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_score', full_name='mediapipe.autoflip.SignalSettings.min_score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_score', full_name='mediapipe.autoflip.SignalSettings.max_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_required', full_name='mediapipe.autoflip.SignalSettings.is_required', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_required', full_name='mediapipe.autoflip.SignalSettings.only_required', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=588,
)

_SIGNALFUSINGCALCULATOROPTIONS.fields_by_name['signal_settings'].message_type = _SIGNALSETTINGS
_SIGNALSETTINGS.fields_by_name['type'].message_type = mediapipe_dot_examples_dot_desktop_dot_autoflip_dot_autoflip__messages__pb2._SIGNALTYPE
DESCRIPTOR.message_types_by_name['SignalFusingCalculatorOptions'] = _SIGNALFUSINGCALCULATOROPTIONS
DESCRIPTOR.message_types_by_name['SignalSettings'] = _SIGNALSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignalFusingCalculatorOptions = _reflection.GeneratedProtocolMessageType('SignalFusingCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALFUSINGCALCULATOROPTIONS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.signal_fusing_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.SignalFusingCalculatorOptions)
  })
_sym_db.RegisterMessage(SignalFusingCalculatorOptions)

SignalSettings = _reflection.GeneratedProtocolMessageType('SignalSettings', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALSETTINGS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.signal_fusing_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.SignalSettings)
  })
_sym_db.RegisterMessage(SignalSettings)

_SIGNALFUSINGCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _SIGNALFUSINGCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_SIGNALFUSINGCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
