# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/examples/desktop/autoflip/calculators/video_filtering_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/examples/desktop/autoflip/calculators/video_filtering_calculator.proto',
  package='mediapipe.autoflip',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nPmediapipe/examples/desktop/autoflip/calculators/video_filtering_calculator.proto\x12\x12mediapipe.autoflip\x1a$mediapipe/framework/calculator.proto\"\xc0\x04\n\x1fVideoFilteringCalculatorOptions\x12\x1a\n\x0b\x66\x61il_if_any\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x64\n\x13\x61spect_ratio_filter\x18\x02 \x01(\x0b\x32\x45.mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilterH\x00\x1a\xac\x02\n\x11\x41spectRatioFilter\x12\x18\n\x0ctarget_width\x18\x01 \x01(\x05:\x02-1\x12\x19\n\rtarget_height\x18\x02 \x01(\x05:\x02-1\x12\x65\n\x0b\x66ilter_type\x18\x03 \x01(\x0e\x32P.mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter.FilterType\"{\n\nFilterType\x12\x17\n\x13UNKNOWN_FILTER_TYPE\x10\x00\x12 \n\x1cUPPER_ASPECT_RATIO_THRESHOLD\x10\x01\x12 \n\x1cLOWER_ASPECT_RATIO_THRESHOLD\x10\x02\x12\x10\n\x0cNO_FILTERING\x10\x03\x32\x62\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xb1\xc5\xe6\x84\x01 \x01(\x0b\x32\x33.mediapipe.autoflip.VideoFilteringCalculatorOptionsB\x08\n\x06\x66ilter'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])



_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER_FILTERTYPE = _descriptor.EnumDescriptor(
  name='FilterType',
  full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter.FilterType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_FILTER_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPPER_ASPECT_RATIO_THRESHOLD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOWER_ASPECT_RATIO_THRESHOLD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_FILTERING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=486,
  serialized_end=609,
)
_sym_db.RegisterEnumDescriptor(_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER_FILTERTYPE)


_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER = _descriptor.Descriptor(
  name='AspectRatioFilter',
  full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_width', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter.target_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_height', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter.target_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter_type', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter.filter_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER_FILTERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=609,
)

_VIDEOFILTERINGCALCULATOROPTIONS = _descriptor.Descriptor(
  name='VideoFilteringCalculatorOptions',
  full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fail_if_any', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.fail_if_any', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aspect_ratio_filter', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.aspect_ratio_filter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.ext', index=0,
      number=278504113, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='filter', full_name='mediapipe.autoflip.VideoFilteringCalculatorOptions.filter',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=143,
  serialized_end=719,
)

_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER.fields_by_name['filter_type'].enum_type = _VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER_FILTERTYPE
_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER.containing_type = _VIDEOFILTERINGCALCULATOROPTIONS
_VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER_FILTERTYPE.containing_type = _VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER
_VIDEOFILTERINGCALCULATOROPTIONS.fields_by_name['aspect_ratio_filter'].message_type = _VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER
_VIDEOFILTERINGCALCULATOROPTIONS.oneofs_by_name['filter'].fields.append(
  _VIDEOFILTERINGCALCULATOROPTIONS.fields_by_name['aspect_ratio_filter'])
_VIDEOFILTERINGCALCULATOROPTIONS.fields_by_name['aspect_ratio_filter'].containing_oneof = _VIDEOFILTERINGCALCULATOROPTIONS.oneofs_by_name['filter']
DESCRIPTOR.message_types_by_name['VideoFilteringCalculatorOptions'] = _VIDEOFILTERINGCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFilteringCalculatorOptions = _reflection.GeneratedProtocolMessageType('VideoFilteringCalculatorOptions', (_message.Message,), {

  'AspectRatioFilter' : _reflection.GeneratedProtocolMessageType('AspectRatioFilter', (_message.Message,), {
    'DESCRIPTOR' : _VIDEOFILTERINGCALCULATOROPTIONS_ASPECTRATIOFILTER,
    '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.video_filtering_calculator_pb2'
    # @@protoc_insertion_point(class_scope:mediapipe.autoflip.VideoFilteringCalculatorOptions.AspectRatioFilter)
    })
  ,
  'DESCRIPTOR' : _VIDEOFILTERINGCALCULATOROPTIONS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.calculators.video_filtering_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.VideoFilteringCalculatorOptions)
  })
_sym_db.RegisterMessage(VideoFilteringCalculatorOptions)
_sym_db.RegisterMessage(VideoFilteringCalculatorOptions.AspectRatioFilter)

_VIDEOFILTERINGCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _VIDEOFILTERINGCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_VIDEOFILTERINGCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
