# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/framework/calculator_contract_test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/framework/calculator_contract_test.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2mediapipe/framework/calculator_contract_test.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\x8f\x01\n\x1d\x43\x61lculatorContractTestOptions\x12\x16\n\ntest_field\x18\x01 \x01(\x01:\x02-12V\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xb7\xd5\x80Z \x01(\x0b\x32(.mediapipe.CalculatorContractTestOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_CALCULATORCONTRACTTESTOPTIONS = _descriptor.Descriptor(
  name='CalculatorContractTestOptions',
  full_name='mediapipe.CalculatorContractTestOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_field', full_name='mediapipe.CalculatorContractTestOptions.test_field', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.CalculatorContractTestOptions.ext', index=0,
      number=188754615, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=247,
)

DESCRIPTOR.message_types_by_name['CalculatorContractTestOptions'] = _CALCULATORCONTRACTTESTOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculatorContractTestOptions = _reflection.GeneratedProtocolMessageType('CalculatorContractTestOptions', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORCONTRACTTESTOPTIONS,
  '__module__' : 'mediapipe.framework.calculator_contract_test_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.CalculatorContractTestOptions)
  })
_sym_db.RegisterMessage(CalculatorContractTestOptions)

_CALCULATORCONTRACTTESTOPTIONS.extensions_by_name['ext'].message_type = _CALCULATORCONTRACTTESTOPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_CALCULATORCONTRACTTESTOPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
