# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/framework/packet_test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/framework/packet_test.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%mediapipe/framework/packet_test.proto\x12\tmediapipe\",\n\x0fPacketTestProto\x12\n\n\x01x\x18\xf1\r \x03(\x05\x12\r\n\x01y\x18\xf1\x8d\x80\x80\x01 \x03(\x05\"\x1c\n\x0bSimpleProto\x12\r\n\x05value\x18\x01 \x03(\x0c\"X\n\x17SerializationProxyProto\x12\x12\n\nbool_value\x18\x01 \x01(\x08\x12\x13\n\x0b\x66loat_value\x18\x02 \x03(\x02\x12\x14\n\x0cstring_value\x18\x03 \x03(\t'
)




_PACKETTESTPROTO = _descriptor.Descriptor(
  name='PacketTestProto',
  full_name='mediapipe.PacketTestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mediapipe.PacketTestProto.x', index=0,
      number=1777, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='mediapipe.PacketTestProto.y', index=1,
      number=268437233, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=96,
)


_SIMPLEPROTO = _descriptor.Descriptor(
  name='SimpleProto',
  full_name='mediapipe.SimpleProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mediapipe.SimpleProto.value', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=126,
)


_SERIALIZATIONPROXYPROTO = _descriptor.Descriptor(
  name='SerializationProxyProto',
  full_name='mediapipe.SerializationProxyProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='mediapipe.SerializationProxyProto.bool_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='mediapipe.SerializationProxyProto.float_value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='mediapipe.SerializationProxyProto.string_value', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['PacketTestProto'] = _PACKETTESTPROTO
DESCRIPTOR.message_types_by_name['SimpleProto'] = _SIMPLEPROTO
DESCRIPTOR.message_types_by_name['SerializationProxyProto'] = _SERIALIZATIONPROXYPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketTestProto = _reflection.GeneratedProtocolMessageType('PacketTestProto', (_message.Message,), {
  'DESCRIPTOR' : _PACKETTESTPROTO,
  '__module__' : 'mediapipe.framework.packet_test_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.PacketTestProto)
  })
_sym_db.RegisterMessage(PacketTestProto)

SimpleProto = _reflection.GeneratedProtocolMessageType('SimpleProto', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEPROTO,
  '__module__' : 'mediapipe.framework.packet_test_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.SimpleProto)
  })
_sym_db.RegisterMessage(SimpleProto)

SerializationProxyProto = _reflection.GeneratedProtocolMessageType('SerializationProxyProto', (_message.Message,), {
  'DESCRIPTOR' : _SERIALIZATIONPROXYPROTO,
  '__module__' : 'mediapipe.framework.packet_test_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.SerializationProxyProto)
  })
_sym_db.RegisterMessage(SerializationProxyProto)


# @@protoc_insertion_point(module_scope)
