# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/graph_tensors_packet_generator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import packet_generator_pb2 as mediapipe_dot_framework_dot_packet__generator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/graph_tensors_packet_generator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nEmediapipe/calculators/tensorflow/graph_tensors_packet_generator.proto\x12\tmediapipe\x1a*mediapipe/framework/packet_generator.proto\"\xb4\x01\n\"GraphTensorsPacketGeneratorOptions\x12\x12\n\ntensor_tag\x18\x01 \x03(\t\x12\x18\n\x10tensor_num_nodes\x18\x02 \x03(\x05\x32`\n\x03\x65xt\x12!.mediapipe.PacketGeneratorOptions\x18\x96\x80\x87\x44 \x01(\x0b\x32-.mediapipe.GraphTensorsPacketGeneratorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_packet__generator__pb2.DESCRIPTOR,])




_GRAPHTENSORSPACKETGENERATOROPTIONS = _descriptor.Descriptor(
  name='GraphTensorsPacketGeneratorOptions',
  full_name='mediapipe.GraphTensorsPacketGeneratorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_tag', full_name='mediapipe.GraphTensorsPacketGeneratorOptions.tensor_tag', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensor_num_nodes', full_name='mediapipe.GraphTensorsPacketGeneratorOptions.tensor_num_nodes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.GraphTensorsPacketGeneratorOptions.ext', index=0,
      number=142721046, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=309,
)

DESCRIPTOR.message_types_by_name['GraphTensorsPacketGeneratorOptions'] = _GRAPHTENSORSPACKETGENERATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphTensorsPacketGeneratorOptions = _reflection.GeneratedProtocolMessageType('GraphTensorsPacketGeneratorOptions', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHTENSORSPACKETGENERATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.graph_tensors_packet_generator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.GraphTensorsPacketGeneratorOptions)
  })
_sym_db.RegisterMessage(GraphTensorsPacketGeneratorOptions)

_GRAPHTENSORSPACKETGENERATOROPTIONS.extensions_by_name['ext'].message_type = _GRAPHTENSORSPACKETGENERATOROPTIONS
mediapipe_dot_framework_dot_packet__generator__pb2.PacketGeneratorOptions.RegisterExtension(_GRAPHTENSORSPACKETGENERATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
