# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nFmediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xef\x01\n#LappedTensorBufferCalculatorOptions\x12\x13\n\x0b\x62uffer_size\x18\x01 \x01(\x05\x12\x0f\n\x07overlap\x18\x02 \x01(\x05\x12\'\n\x18\x61\x64\x64_batch_dim_to_tensors\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x10timestamp_offset\x18\x04 \x01(\x05:\x01\x30\x32\\\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xd4\xdb\xc6S \x01(\x0b\x32..mediapipe.LappedTensorBufferCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_LAPPEDTENSORBUFFERCALCULATOROPTIONS = _descriptor.Descriptor(
  name='LappedTensorBufferCalculatorOptions',
  full_name='mediapipe.LappedTensorBufferCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer_size', full_name='mediapipe.LappedTensorBufferCalculatorOptions.buffer_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overlap', full_name='mediapipe.LappedTensorBufferCalculatorOptions.overlap', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_batch_dim_to_tensors', full_name='mediapipe.LappedTensorBufferCalculatorOptions.add_batch_dim_to_tensors', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_offset', full_name='mediapipe.LappedTensorBufferCalculatorOptions.timestamp_offset', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.LappedTensorBufferCalculatorOptions.ext', index=0,
      number=175222228, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=363,
)

DESCRIPTOR.message_types_by_name['LappedTensorBufferCalculatorOptions'] = _LAPPEDTENSORBUFFERCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LappedTensorBufferCalculatorOptions = _reflection.GeneratedProtocolMessageType('LappedTensorBufferCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _LAPPEDTENSORBUFFERCALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.lapped_tensor_buffer_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.LappedTensorBufferCalculatorOptions)
  })
_sym_db.RegisterMessage(LappedTensorBufferCalculatorOptions)

_LAPPEDTENSORBUFFERCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _LAPPEDTENSORBUFFERCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_LAPPEDTENSORBUFFERCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
