# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/matrix_to_tensor_calculator_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/matrix_to_tensor_calculator_options.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nJmediapipe/calculators/tensorflow/matrix_to_tensor_calculator_options.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xbc\x01\n\x1fMatrixToTensorCalculatorOptions\x12\x18\n\ttranspose\x18\x01 \x01(\x08:\x05\x66\x61lse\x12%\n\x16\x61\x64\x64_trailing_dimension\x18\x02 \x01(\x08:\x05\x66\x61lse2X\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\x83\xa4\xae> \x01(\x0b\x32*.mediapipe.MatrixToTensorCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_MATRIXTOTENSORCALCULATOROPTIONS = _descriptor.Descriptor(
  name='MatrixToTensorCalculatorOptions',
  full_name='mediapipe.MatrixToTensorCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transpose', full_name='mediapipe.MatrixToTensorCalculatorOptions.transpose', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add_trailing_dimension', full_name='mediapipe.MatrixToTensorCalculatorOptions.add_trailing_dimension', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.MatrixToTensorCalculatorOptions.ext', index=0,
      number=130781699, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['MatrixToTensorCalculatorOptions'] = _MATRIXTOTENSORCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatrixToTensorCalculatorOptions = _reflection.GeneratedProtocolMessageType('MatrixToTensorCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXTOTENSORCALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.matrix_to_tensor_calculator_options_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.MatrixToTensorCalculatorOptions)
  })
_sym_db.RegisterMessage(MatrixToTensorCalculatorOptions)

_MATRIXTOTENSORCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _MATRIXTOTENSORCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_MATRIXTOTENSORCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
