# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/tensor_squeeze_dimensions_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/tensor_squeeze_dimensions_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nKmediapipe/calculators/tensorflow/tensor_squeeze_dimensions_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xc2\x01\n(TensorSqueezeDimensionsCalculatorOptions\x12&\n\x17squeeze_all_single_dims\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x0b\n\x03\x64im\x18\x02 \x03(\x05\x32\x61\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xdd\xef\x90\x37 \x01(\x0b\x32\x33.mediapipe.TensorSqueezeDimensionsCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS = _descriptor.Descriptor(
  name='TensorSqueezeDimensionsCalculatorOptions',
  full_name='mediapipe.TensorSqueezeDimensionsCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='squeeze_all_single_dims', full_name='mediapipe.TensorSqueezeDimensionsCalculatorOptions.squeeze_all_single_dims', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='mediapipe.TensorSqueezeDimensionsCalculatorOptions.dim', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.TensorSqueezeDimensionsCalculatorOptions.ext', index=0,
      number=115619805, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['TensorSqueezeDimensionsCalculatorOptions'] = _TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorSqueezeDimensionsCalculatorOptions = _reflection.GeneratedProtocolMessageType('TensorSqueezeDimensionsCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.tensor_squeeze_dimensions_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TensorSqueezeDimensionsCalculatorOptions)
  })
_sym_db.RegisterMessage(TensorSqueezeDimensionsCalculatorOptions)

_TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_TENSORSQUEEZEDIMENSIONSCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
