# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/tensor_to_matrix_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2
from mediapipe.framework.formats import time_series_header_pb2 as mediapipe_dot_framework_dot_formats_dot_time__series__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/tensor_to_matrix_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBmediapipe/calculators/tensorflow/tensor_to_matrix_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\x1a\x34mediapipe/framework/formats/time_series_header.proto\"\xbe\x01\n\x1fTensorToMatrixCalculatorOptions\x12\x41\n\x1ctime_series_header_overrides\x18\x01 \x01(\x0b\x32\x1b.mediapipe.TimeSeriesHeader2X\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xe8\xd9\x94\x41 \x01(\x0b\x32*.mediapipe.TensorToMatrixCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_formats_dot_time__series__header__pb2.DESCRIPTOR,])




_TENSORTOMATRIXCALCULATOROPTIONS = _descriptor.Descriptor(
  name='TensorToMatrixCalculatorOptions',
  full_name='mediapipe.TensorToMatrixCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_series_header_overrides', full_name='mediapipe.TensorToMatrixCalculatorOptions.time_series_header_overrides', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.TensorToMatrixCalculatorOptions.ext', index=0,
      number=136654056, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=364,
)

_TENSORTOMATRIXCALCULATOROPTIONS.fields_by_name['time_series_header_overrides'].message_type = mediapipe_dot_framework_dot_formats_dot_time__series__header__pb2._TIMESERIESHEADER
DESCRIPTOR.message_types_by_name['TensorToMatrixCalculatorOptions'] = _TENSORTOMATRIXCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorToMatrixCalculatorOptions = _reflection.GeneratedProtocolMessageType('TensorToMatrixCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _TENSORTOMATRIXCALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.tensor_to_matrix_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TensorToMatrixCalculatorOptions)
  })
_sym_db.RegisterMessage(TensorToMatrixCalculatorOptions)

_TENSORTOMATRIXCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _TENSORTOMATRIXCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_TENSORTOMATRIXCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
