# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/unpack_media_sequence_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.calculators.core import packet_resampler_calculator_pb2 as mediapipe_dot_calculators_dot_core_dot_packet__resampler__calculator__pb2
from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2
from mediapipe.util import audio_decoder_pb2 as mediapipe_dot_util_dot_audio__decoder__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/unpack_media_sequence_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nGmediapipe/calculators/tensorflow/unpack_media_sequence_calculator.proto\x12\tmediapipe\x1a<mediapipe/calculators/core/packet_resampler_calculator.proto\x1a$mediapipe/framework/calculator.proto\x1a\"mediapipe/util/audio_decoder.proto\"\xd1\x03\n$UnpackMediaSequenceCalculatorOptions\x12\x1e\n\x16\x64\x61taset_root_directory\x18\x01 \x01(\t\x12\x1c\n\x14padding_before_label\x18\x03 \x01(\x02\x12\x1b\n\x13padding_after_label\x18\x04 \x01(\x02\x12+\n extra_padding_from_media_decoder\x18\x05 \x01(\x02:\x01\x30\x12R\n\x1d\x62\x61se_packet_resampler_options\x18\x06 \x01(\x0b\x32+.mediapipe.PacketResamplerCalculatorOptions\x12*\n\"force_decoding_from_start_of_media\x18\x07 \x01(\x08\x12\x42\n\x1a\x62\x61se_audio_decoder_options\x18\t \x01(\x0b\x32\x1e.mediapipe.AudioDecoderOptions2]\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\x91\xd9\xc5t \x01(\x0b\x32/.mediapipe.UnpackMediaSequenceCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_calculators_dot_core_dot_packet__resampler__calculator__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,mediapipe_dot_util_dot_audio__decoder__pb2.DESCRIPTOR,])




_UNPACKMEDIASEQUENCECALCULATOROPTIONS = _descriptor.Descriptor(
  name='UnpackMediaSequenceCalculatorOptions',
  full_name='mediapipe.UnpackMediaSequenceCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_root_directory', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.dataset_root_directory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding_before_label', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.padding_before_label', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='padding_after_label', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.padding_after_label', index=2,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_padding_from_media_decoder', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.extra_padding_from_media_decoder', index=3,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_packet_resampler_options', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.base_packet_resampler_options', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_decoding_from_start_of_media', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.force_decoding_from_start_of_media', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_audio_decoder_options', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.base_audio_decoder_options', index=6,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.UnpackMediaSequenceCalculatorOptions.ext', index=0,
      number=244411537, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=688,
)

_UNPACKMEDIASEQUENCECALCULATOROPTIONS.fields_by_name['base_packet_resampler_options'].message_type = mediapipe_dot_calculators_dot_core_dot_packet__resampler__calculator__pb2._PACKETRESAMPLERCALCULATOROPTIONS
_UNPACKMEDIASEQUENCECALCULATOROPTIONS.fields_by_name['base_audio_decoder_options'].message_type = mediapipe_dot_util_dot_audio__decoder__pb2._AUDIODECODEROPTIONS
DESCRIPTOR.message_types_by_name['UnpackMediaSequenceCalculatorOptions'] = _UNPACKMEDIASEQUENCECALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnpackMediaSequenceCalculatorOptions = _reflection.GeneratedProtocolMessageType('UnpackMediaSequenceCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _UNPACKMEDIASEQUENCECALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.unpack_media_sequence_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.UnpackMediaSequenceCalculatorOptions)
  })
_sym_db.RegisterMessage(UnpackMediaSequenceCalculatorOptions)

_UNPACKMEDIASEQUENCECALCULATOROPTIONS.extensions_by_name['ext'].message_type = _UNPACKMEDIASEQUENCECALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_UNPACKMEDIASEQUENCECALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
