# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/calculators/tensorflow/vector_float_to_tensor_calculator_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/calculators/tensorflow/vector_float_to_tensor_calculator_options.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nPmediapipe/calculators/tensorflow/vector_float_to_tensor_calculator_options.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xae\x02\n$VectorFloatToTensorCalculatorOptions\x12W\n\ninput_size\x18\x01 \x01(\x0e\x32\x39.mediapipe.VectorFloatToTensorCalculatorOptions.InputSize:\x08INPUT_1D\x12\x18\n\ttranspose\x18\x02 \x01(\x08:\x05\x66\x61lse\"4\n\tInputSize\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08INPUT_1D\x10\x01\x12\x0c\n\x08INPUT_2D\x10\x02\x32]\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\x91\x98\x85\x41 \x01(\x0b\x32/.mediapipe.VectorFloatToTensorCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])



_VECTORFLOATTOTENSORCALCULATOROPTIONS_INPUTSIZE = _descriptor.EnumDescriptor(
  name='InputSize',
  full_name='mediapipe.VectorFloatToTensorCalculatorOptions.InputSize',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPUT_1D', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPUT_2D', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=289,
  serialized_end=341,
)
_sym_db.RegisterEnumDescriptor(_VECTORFLOATTOTENSORCALCULATOROPTIONS_INPUTSIZE)


_VECTORFLOATTOTENSORCALCULATOROPTIONS = _descriptor.Descriptor(
  name='VectorFloatToTensorCalculatorOptions',
  full_name='mediapipe.VectorFloatToTensorCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_size', full_name='mediapipe.VectorFloatToTensorCalculatorOptions.input_size', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transpose', full_name='mediapipe.VectorFloatToTensorCalculatorOptions.transpose', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.VectorFloatToTensorCalculatorOptions.ext', index=0,
      number=136399889, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
    _VECTORFLOATTOTENSORCALCULATOROPTIONS_INPUTSIZE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=436,
)

_VECTORFLOATTOTENSORCALCULATOROPTIONS.fields_by_name['input_size'].enum_type = _VECTORFLOATTOTENSORCALCULATOROPTIONS_INPUTSIZE
_VECTORFLOATTOTENSORCALCULATOROPTIONS_INPUTSIZE.containing_type = _VECTORFLOATTOTENSORCALCULATOROPTIONS
DESCRIPTOR.message_types_by_name['VectorFloatToTensorCalculatorOptions'] = _VECTORFLOATTOTENSORCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VectorFloatToTensorCalculatorOptions = _reflection.GeneratedProtocolMessageType('VectorFloatToTensorCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _VECTORFLOATTOTENSORCALCULATOROPTIONS,
  '__module__' : 'mediapipe.calculators.tensorflow.vector_float_to_tensor_calculator_options_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.VectorFloatToTensorCalculatorOptions)
  })
_sym_db.RegisterMessage(VectorFloatToTensorCalculatorOptions)

_VECTORFLOATTOTENSORCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _VECTORFLOATTOTENSORCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_VECTORFLOATTOTENSORCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
