# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n_mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xc7\x01\n+AnnotationsToModelMatricesCalculatorOptions\x12\x13\n\x0bmodel_scale\x18\x01 \x03(\x02\x12\x1c\n\x14model_transformation\x18\x02 \x03(\x02\x32\x65\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\x8b\xac\xae\x8a\x01 \x01(\x0b\x32\x36.mediapipe.AnnotationsToModelMatricesCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])




_ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS = _descriptor.Descriptor(
  name='AnnotationsToModelMatricesCalculatorOptions',
  full_name='mediapipe.AnnotationsToModelMatricesCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_scale', full_name='mediapipe.AnnotationsToModelMatricesCalculatorOptions.model_scale', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_transformation', full_name='mediapipe.AnnotationsToModelMatricesCalculatorOptions.model_transformation', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.AnnotationsToModelMatricesCalculatorOptions.ext', index=0,
      number=290166283, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=348,
)

DESCRIPTOR.message_types_by_name['AnnotationsToModelMatricesCalculatorOptions'] = _ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotationsToModelMatricesCalculatorOptions = _reflection.GeneratedProtocolMessageType('AnnotationsToModelMatricesCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS,
  '__module__' : 'mediapipe.graphs.object_detection_3d.calculators.annotations_to_model_matrices_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.AnnotationsToModelMatricesCalculatorOptions)
  })
_sym_db.RegisterMessage(AnnotationsToModelMatricesCalculatorOptions)

_ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_ANNOTATIONSTOMODELMATRICESCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
