# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/graphs/object_detection_3d/calculators/model_matrix.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/graphs/object_detection_3d/calculators/model_matrix.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nCmediapipe/graphs/object_detection_3d/calculators/model_matrix.proto\x12\tmediapipe\"Y\n\x15TimedModelMatrixProto\x12\x1a\n\x0ematrix_entries\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x14\n\ttime_msec\x18\x02 \x01(\x03:\x01\x30\x12\x0e\n\x02id\x18\x03 \x01(\x05:\x02-1\"S\n\x19TimedModelMatrixProtoList\x12\x36\n\x0cmodel_matrix\x18\x01 \x03(\x0b\x32 .mediapipe.TimedModelMatrixProto\"T\n\x10TimedVectorProto\x12\x1a\n\x0evector_entries\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x14\n\ttime_msec\x18\x02 \x01(\x03:\x01\x30\x12\x0e\n\x02id\x18\x03 \x01(\x05:\x02-1\"H\n\x14TimedVectorProtoList\x12\x30\n\x0bvector_list\x18\x01 \x03(\x0b\x32\x1b.mediapipe.TimedVectorProto'
)




_TIMEDMODELMATRIXPROTO = _descriptor.Descriptor(
  name='TimedModelMatrixProto',
  full_name='mediapipe.TimedModelMatrixProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix_entries', full_name='mediapipe.TimedModelMatrixProto.matrix_entries', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_msec', full_name='mediapipe.TimedModelMatrixProto.time_msec', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='mediapipe.TimedModelMatrixProto.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=171,
)


_TIMEDMODELMATRIXPROTOLIST = _descriptor.Descriptor(
  name='TimedModelMatrixProtoList',
  full_name='mediapipe.TimedModelMatrixProtoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_matrix', full_name='mediapipe.TimedModelMatrixProtoList.model_matrix', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=256,
)


_TIMEDVECTORPROTO = _descriptor.Descriptor(
  name='TimedVectorProto',
  full_name='mediapipe.TimedVectorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_entries', full_name='mediapipe.TimedVectorProto.vector_entries', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_msec', full_name='mediapipe.TimedVectorProto.time_msec', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='mediapipe.TimedVectorProto.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=342,
)


_TIMEDVECTORPROTOLIST = _descriptor.Descriptor(
  name='TimedVectorProtoList',
  full_name='mediapipe.TimedVectorProtoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_list', full_name='mediapipe.TimedVectorProtoList.vector_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=416,
)

_TIMEDMODELMATRIXPROTOLIST.fields_by_name['model_matrix'].message_type = _TIMEDMODELMATRIXPROTO
_TIMEDVECTORPROTOLIST.fields_by_name['vector_list'].message_type = _TIMEDVECTORPROTO
DESCRIPTOR.message_types_by_name['TimedModelMatrixProto'] = _TIMEDMODELMATRIXPROTO
DESCRIPTOR.message_types_by_name['TimedModelMatrixProtoList'] = _TIMEDMODELMATRIXPROTOLIST
DESCRIPTOR.message_types_by_name['TimedVectorProto'] = _TIMEDVECTORPROTO
DESCRIPTOR.message_types_by_name['TimedVectorProtoList'] = _TIMEDVECTORPROTOLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimedModelMatrixProto = _reflection.GeneratedProtocolMessageType('TimedModelMatrixProto', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDMODELMATRIXPROTO,
  '__module__' : 'mediapipe.graphs.object_detection_3d.calculators.model_matrix_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TimedModelMatrixProto)
  })
_sym_db.RegisterMessage(TimedModelMatrixProto)

TimedModelMatrixProtoList = _reflection.GeneratedProtocolMessageType('TimedModelMatrixProtoList', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDMODELMATRIXPROTOLIST,
  '__module__' : 'mediapipe.graphs.object_detection_3d.calculators.model_matrix_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TimedModelMatrixProtoList)
  })
_sym_db.RegisterMessage(TimedModelMatrixProtoList)

TimedVectorProto = _reflection.GeneratedProtocolMessageType('TimedVectorProto', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDVECTORPROTO,
  '__module__' : 'mediapipe.graphs.object_detection_3d.calculators.model_matrix_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TimedVectorProto)
  })
_sym_db.RegisterMessage(TimedVectorProto)

TimedVectorProtoList = _reflection.GeneratedProtocolMessageType('TimedVectorProtoList', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDVECTORPROTOLIST,
  '__module__' : 'mediapipe.graphs.object_detection_3d.calculators.model_matrix_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.TimedVectorProtoList)
  })
_sym_db.RegisterMessage(TimedVectorProtoList)


_TIMEDMODELMATRIXPROTO.fields_by_name['matrix_entries']._options = None
_TIMEDVECTORPROTO.fields_by_name['vector_entries']._options = None
# @@protoc_insertion_point(module_scope)
