# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/framework/testdata/night_light_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
try:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
except AttributeError:
  mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/framework/testdata/night_light_calculator.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9mediapipe/framework/testdata/night_light_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\xec\x02\n\x1bNightLightCalculatorOptions\x12\x12\n\nframe_rate\x18\x01 \x01(\x01\x12J\n\routput_header\x18\x02 \x01(\x0e\x32\x33.mediapipe.NightLightCalculatorOptions.OutputHeader\x12\x0e\n\x06jitter\x18\x04 \x01(\x01\x12\x16\n\x0e\x62\x61se_timestamp\x18\x05 \x03(\x03\x12\x14\n\x0cround_limits\x18\x08 \x01(\x08\x12\x15\n\rformat_string\x18\t \x01(\t\"B\n\x0cOutputHeader\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bPASS_HEADER\x10\x01\x12\x17\n\x13UPDATE_VIDEO_HEADER\x10\x02\x32T\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\x8f\xc2\x81[ \x01(\x0b\x32&.mediapipe.NightLightCalculatorOptions'
  ,
  dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])



_NIGHTLIGHTCALCULATOROPTIONS_OUTPUTHEADER = _descriptor.EnumDescriptor(
  name='OutputHeader',
  full_name='mediapipe.NightLightCalculatorOptions.OutputHeader',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PASS_HEADER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_VIDEO_HEADER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=323,
  serialized_end=389,
)
_sym_db.RegisterEnumDescriptor(_NIGHTLIGHTCALCULATOROPTIONS_OUTPUTHEADER)


_NIGHTLIGHTCALCULATOROPTIONS = _descriptor.Descriptor(
  name='NightLightCalculatorOptions',
  full_name='mediapipe.NightLightCalculatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_rate', full_name='mediapipe.NightLightCalculatorOptions.frame_rate', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_header', full_name='mediapipe.NightLightCalculatorOptions.output_header', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jitter', full_name='mediapipe.NightLightCalculatorOptions.jitter', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_timestamp', full_name='mediapipe.NightLightCalculatorOptions.base_timestamp', index=3,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_limits', full_name='mediapipe.NightLightCalculatorOptions.round_limits', index=4,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format_string', full_name='mediapipe.NightLightCalculatorOptions.format_string', index=5,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='mediapipe.NightLightCalculatorOptions.ext', index=0,
      number=190865679, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
    _NIGHTLIGHTCALCULATOROPTIONS_OUTPUTHEADER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=475,
)

_NIGHTLIGHTCALCULATOROPTIONS.fields_by_name['output_header'].enum_type = _NIGHTLIGHTCALCULATOROPTIONS_OUTPUTHEADER
_NIGHTLIGHTCALCULATOROPTIONS_OUTPUTHEADER.containing_type = _NIGHTLIGHTCALCULATOROPTIONS
DESCRIPTOR.message_types_by_name['NightLightCalculatorOptions'] = _NIGHTLIGHTCALCULATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NightLightCalculatorOptions = _reflection.GeneratedProtocolMessageType('NightLightCalculatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _NIGHTLIGHTCALCULATOROPTIONS,
  '__module__' : 'mediapipe.framework.testdata.night_light_calculator_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.NightLightCalculatorOptions)
  })
_sym_db.RegisterMessage(NightLightCalculatorOptions)

_NIGHTLIGHTCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _NIGHTLIGHTCALCULATOROPTIONS
mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_NIGHTLIGHTCALCULATOROPTIONS.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
