# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/framework/testdata/zoo_mutation_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mediapipe.framework import packet_generator_pb2 as mediapipe_dot_framework_dot_packet__generator__pb2
from mediapipe.framework.testdata import zoo_mutator_pb2 as mediapipe_dot_framework_dot_testdata_dot_zoo__mutator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/framework/testdata/zoo_mutation_calculator.proto',
  package='google_zoo',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:mediapipe/framework/testdata/zoo_mutation_calculator.proto\x12\ngoogle_zoo\x1a*mediapipe/framework/packet_generator.proto\x1a.mediapipe/framework/testdata/zoo_mutator.proto:b\n\x16zoo_mutator_config_ext\x12!.mediapipe.PacketGeneratorOptions\x18\xd6\xf6\x95p \x01(\x0b\x32\x1c.google_zoo.ZooMutatorConfig'
  ,
  dependencies=[mediapipe_dot_framework_dot_packet__generator__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_testdata_dot_zoo__mutator__pb2.DESCRIPTOR,])


ZOO_MUTATOR_CONFIG_EXT_FIELD_NUMBER = 235240278
zoo_mutator_config_ext = _descriptor.FieldDescriptor(
  name='zoo_mutator_config_ext', full_name='google_zoo.zoo_mutator_config_ext', index=0,
  number=235240278, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['zoo_mutator_config_ext'] = zoo_mutator_config_ext
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

zoo_mutator_config_ext.message_type = mediapipe_dot_framework_dot_testdata_dot_zoo__mutator__pb2._ZOOMUTATORCONFIG
mediapipe_dot_framework_dot_packet__generator__pb2.PacketGeneratorOptions.RegisterExtension(zoo_mutator_config_ext)

# @@protoc_insertion_point(module_scope)
