# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/examples/desktop/autoflip/quality/kinematic_path_solver.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/examples/desktop/autoflip/quality/kinematic_path_solver.proto',
  package='mediapipe.autoflip',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nGmediapipe/examples/desktop/autoflip/quality/kinematic_path_solver.proto\x12\x12mediapipe.autoflip\"j\n\x10KinematicOptions\x12\x18\n\x0bupdate_rate\x18\x01 \x01(\x01:\x03\x30.5\x12\x18\n\x0cmax_velocity\x18\x02 \x01(\x01:\x02\x31\x38\x12\"\n\x15min_motion_to_reframe\x18\x03 \x01(\x02:\x03\x31.8'
)




_KINEMATICOPTIONS = _descriptor.Descriptor(
  name='KinematicOptions',
  full_name='mediapipe.autoflip.KinematicOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='update_rate', full_name='mediapipe.autoflip.KinematicOptions.update_rate', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_velocity', full_name='mediapipe.autoflip.KinematicOptions.max_velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(18),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_motion_to_reframe', full_name='mediapipe.autoflip.KinematicOptions.min_motion_to_reframe', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1.8),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['KinematicOptions'] = _KINEMATICOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KinematicOptions = _reflection.GeneratedProtocolMessageType('KinematicOptions', (_message.Message,), {
  'DESCRIPTOR' : _KINEMATICOPTIONS,
  '__module__' : 'mediapipe.examples.desktop.autoflip.quality.kinematic_path_solver_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.autoflip.KinematicOptions)
  })
_sym_db.RegisterMessage(KinematicOptions)


# @@protoc_insertion_point(module_scope)
