node {
  calculator: "ProducerCalculator"
  output_stream: "data"
}

node {
    calculator: "SubGraphPassThroughCalculator"
    input_stream: "INPUT:data"
    output_stream: "OUTPUT:out"
}

node {
  calculator: "ConsumerCalculator"
  input_stream: "out"
}
