type: "SubGraphPassThroughCalculator"

input_stream: "INPUT:in"
output_stream: "OUTPUT:out"

input_side_packet: "INPUT_PACKET:in_packet"
output_side_packet: "OUTPUT_PACKET:out_packet"

node {
  calculator: "PassThroughCalculator"
  input_stream: "in"
  output_stream: "out"
  input_side_packet: "in_packet"
  output_side_packet: "out_packet"
}